Add : products 앱 view 작성 (상품목록, 상세페이지)
wecode-bootcamp-korea/25-1st-NULLFICTION-backend pull request #4
Opened 2021-10-11 06:58 UTC by palza4dev

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카테고리별 상품 목록과 상품별 상세 페이지 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 전체 및 카테고리별 상품 목록
- 카테고리 id를 query parameter로 받기 위해 `request.GET.get()` 사용
- Product 모델에서 역참조하여 접근 -> Q객체 활용 (추후 리팩토링시 변수화 고려)

2. 판매량순으로 best-seller 카테고리 구현
- 상품별 판매수량 합계를 구하기 위해 `annotate()` 사용 -> 주문상품 테이블(order_items)의 quantity로 역참조 접근
- 판매수량 내림차순 정렬
- query parameter의 값(ex: n)에 따라 상위 판매 상품 n개를 전송

3. 상품명 검색 기능
- Q객체를 통해 filter에 두가지 조건을 넣을 수 있었으며, 대소문자를 구분하지 않도록 icontains 활용
- keyword의 검색 대상은 상품명 name 혹은 콜렉션명 collection_name

4. 상품별 상세 페이지
- `request.GET.get()`을 사용해 상품의 id를 받아옴
- 상품 이미지는 product_image 테이블을 역참조하여 for문으로 썸네일을 첫번째로 하는 배열로 가져옴
- 상품의 향 정보는 scent 테이블을 역참조하여 for문으로 가져옴

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- request로 받아온 정보를 기준으로 상품을 찾으려면 for문을 이용해야 했으나, Q객체로 SQL query를 줄였습니다.
- 판매수량 계산을 위한 임시테이블이 필요해서 annotate를 사용했으나 더 공부할 필요가 있습니다.
- for문과 List Comprehension의 차이에 대해 알 수 있었습니다.
- 한번에 너무 많은 기능을 작성한거 같아서, 커밋과 푸시 단위에 대해 고민해봐야 겠습니다.

<br />

## :: 기타 질문 및 특이 사항
- 상품 상세View로 라우팅시 `<int:product_id>` 이런 식으로 받아서 get 함수의 인자로 쓰고 싶었으나 실패했습니다.
- 위 상황에서 에러가 안나고 계속 상품전체View로 라우팅되어서 원인 파악이 힘들었습니다.

## :: API 테스트 상황을 기록하기 위한 POST 문서
https://documenter.getpostman.com/view/17676214/UUy7ajLu

2021-10-11 09:12 UTC, palza4dev commented on products/views.py
> +    def get(self, request):
아래 코드로 해보고 있는데 어느 부분이 틀린건지 아직도 모르겠습니다...ㅜㅜ

```python
# products/urls
path('/<int:product_id>', ProductDetailView.as_view())

# products/views
class ProductDetailView(View):
    def get(self, request, product_id):
        product = Product.objects.get(id=product_id)
```
http 요청
127.0.0.1:8000/products/product_id=2

2021-10-11 09:21 UTC, palza4dev commented on products/views.py
> +    def get(self, request):
찾아냈습니다!!!
HTTP 요청 양식이 문제였습니다.
아래 요청으로 상세 조회가 가능했습니다
127.0.0.1:8000/products/1

2021-10-12 01:16 UTC, kyeongraekim requested changes
상품 뷰 관련 거의 마지막 리뷰가 될 것 같네요!~ 아래 수정사항 참고하셔서 반영해보세요!

2021-10-12 01:16 UTC, kyeongraekim commented on products/views.py
> +class ProductView(View):
네 잘 반영해주셨네요!~ 다만 장고 코어에서 paginator를 import 하는 방법 말고, 
시간적 여유가 되신다면 페이지네이션의 원리를 보다 더 잘 파악할 수 있게 별도의 라이브러리나 모듈의 도움없이 직접 offset, limit 값을 받아서 진행해보세요!~

2021-10-12 01:16 UTC, kyeongraekim commented on products/views.py
> +            if main_category != None:
제가 의도드렸던 내용은`if main_category and main_category != None`: 이었습니다만.. 
이렇게 코드상의 논리적 공백 작성을 지양하는 것은 개발자 성향마다 다를 순 있겠습니다 ㅎㅎ
승준님의 선택에 따라 if main_category 부분만 남길지 아니면 뒤에 != None이 굳이 필요 없다고 판단되시면 빼볼지 판단해보세요!

2021-10-12 01:16 UTC, kyeongraekim commented on products/urls.py
> +    path('/<int:product_id>', ProductDetailView.as_view()),
그리고 이곳에서 실수하셨던 내용은 path parameter로 값을 받아오게 하려했으니 실제로 URI 호출시 작성한 내용은 query parameter 였었던 것 같네요! 일단 문제 해결이 되었다니 다행입니다!

2021-10-12 01:22 UTC, palza4dev commented on products/urls.py
> +    path('/<int:product_id>', ProductDetailView.as_view()),
네 path와 query parameter 부분은 다시 정리해서 블로깅을 할 예정입니다!

2021-10-12 01:33 UTC, palza4dev commented on products/views.py
> +            if main_category != None:
말씀하신 형태로 바꾸겠습니다.
지금은 저 스스로 코드를 보고 바로 이해가 되지만, 시간이 지나거나 다른 사람이 보게되었을때 명확히 이해할 수 있는 것도 중요하다고 생각합니다.

2021-10-12 01:36 UTC, palza4dev commented on products/views.py
> +class ProductView(View):
네 프론트엔드측과 협의해보고 우선 순위를 정할 예정입니다!

2021-10-12 14:34 UTC, kyeongraekim requested changes
승준님 작은 수정사항 하나 발견해서 리뷰 드립니다~

2021-10-12 14:34 UTC, kyeongraekim commented on products/views.py
> +            if (main_category or best_seller or sub_category or scent or keyword or page_number) == None:
이곳은 or 가 아니고 전체를 and로 묶어야 맞는 로직이지 않을까요? 위에 걸러서 들어올 모든 조건값들이 만일 None 이라면 아무런 필터링 없이 전체 Product를 받아와야 하는 로직이 되어야 할 것 같네요~

2021-10-12 23:55 UTC, palza4dev commented on products/views.py
> +class ProductView(View):
프론트엔드와 맞추지 않더라도 전송하는 정보의 제한을 둬야할 것 같아서 작성할 예정입니다!

2021-10-13 01:20 UTC, palza4dev commented on products/views.py
> +            if (main_category or best_seller or sub_category or scent or keyword or page_number) == None:
```python
if (main_category and best_seller and sub_category and scent and keyword and page_number) == None:
                products = Product.objects.all()
```
이렇게 묶어주는게 맞다고 생각하는데
하나라도 값이 들어오는 경우에 자꾸 전체 상품이 조회됩니다.
제가 어떤 부분을 놓친걸까요?

2021-10-13 02:16 UTC, merged